---
title: "Communicating with Data via R markdown"
subtitle: "\u2728 Pretty Presentations \u2728"
author: "Emi Tanaka"
email: "dr.emi.tanaka@gmail.com"
date: "4th October 2019 | COMBINE | Sydney, Australia"
length: "90 minutes"
pdflink: "link"
titleslide_bgimg: "images/bg3.jpg"
color_theme: "#FC427B"
output:
  xaringan::moon_reader:
    css: [ninjutsu, "assets/animate.css", "assets/cssgrid.css", "assets/custom.css", ]
    self_contained: false # if true, fonts will be stored locally
    seal: false # show a title slide with YAML information
    #yolo: false # show Karl randomly
    chakra: 'libs/remark-latest.min.js'
    beforeInit: "assets/custom.js"
    lib_dir: libs
    includes:
      in_header: "assets/custom.html"
      # before_body: 
      after_body: "assets/remarkjs_extended.html"
      # includes
    mathjax: "assets/mathjax-local/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
    nature:
      # autoplay: 100 # in milliseconds to play next slide
      # coundown: 100 # to display on each slide (TRUE if autoplay on)
      # titleSlideClass: c("center", "middle", "inverse")
      highlightStyle: github # [arta, ascetic, dark, default, far, github, googlecode, idea, ir-black, magula, monokai, rainbow, solarized-dark, solarized-light, sunburst, tomorrow, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night, tomorrow-night-eighties, vs, zenburn.]
      highlightLanguage: r # no-highlight to disable
      highlightLines: true
      highlightSpans: false # true: use `backticks` as delimiters.
      countIncrementalSlides: false
      slideNumberFormat: '%current%/%total%'
      navigation:
        scroll: false # disable scrolling to navigate slides
        touch: true
        click: false
      ratio: '16:9' # ['4:3', '13:9']
---


```{r external, child="setup.Rmd", include=FALSE}
```

```{r titleslide, child="titleslide.Rmd"}
```

---

```{r checklist}
checklist <- c("Do this")
```

```{r endslide, child="endslide.Rmd"}
```
